### ISSUE TITLE
AP Implementation

### ISSUE THREAD

**Issue by Capruce** [coldAmphibian/Defense-of-the-Legends#11]
I've been thinking about how we will handle AP?

Originally, I simply assigned a .ap to each hero on spawn and then tested for it within my spells however that makes it hard to see what ap you have. Therefore, I copied the way legion commander did it and added an AP modifier that stacks with your ap. I also added in functions to each caster on spawn that let you simply hero:GetAbilityPower() and hero:SetAbilityPower(amount). It's useful for now but I imagine we will want to change that in the future.

I have finished veigar's abilities (hence all the work with AP) however I'm also trying my hand at particle effects, who knows where it goes.

**Comment by wfzyx** [comment]
A simple and usefull way is to define a class based on hero baseclass, called "champion"

in this class we can implement these GetAP and SetAP methods and also assign internally with a variable.

to show for the player, a panorama ui need to be done and accessed via lua api
