### ISSUE TITLE
Subreddit is Live

### ISSUE THREAD

**Issue by wn-mitch** [coldAmphibian/Defense-of-the-Legends#13]
I'm the sole mod on the subreddit, which can be found here: https://www.reddit.com/r/DefenseoftheLegends/

I currently have posts restricted to approved submitters only. I'll mod anyone who's currently working on the project and flair you with a dev tag. I'll get working on the CSS sometime this week to get Dev tags and the like added in. Sorry for making this an issue, this is the only way I could get in touch with everyone.

**Comment by wfzyx** [comment]
(_rammus voice_) "Ok"

**Comment by coldAmphibian** [comment]
my account name is the same as it is here, except there's an underscore between the words.

**Comment by Zarthbenn** [comment]
same name as username: Zarthbenn. I commented in that thread

**Comment by wfzyx** [comment]
Archived
