### ISSUE TITLE
Taking champion model import requests

### ISSUE THREAD

**Issue by Zarthbenn** [coldAmphibian/Defense-of-the-Legends#17]
I think I have a good grasp on reliably porting the champion models into dota. There are some exceptions with weird and broken animations (only encountered this with sona so far) but im working on fixing those as well.

If anyone has a champ they are working on or a champ model (and animations) they would like imported and dont know how to just post here or contact me by email and I will help out.

(not sure if there is somewhere else I should post this but this repo is the best way to contact everyone)

**Comment by wfzyx** [comment]
Summoning @coldAmphibian

**Comment by Zarthbenn** [comment]
did I do something wrong o.o

**Comment by wfzyx** [comment]
Nops, but he already have his extract workflow, and maybe you two can work together to make a new workflow even better, merging the better of your jobs.

**Comment by Zarthbenn** [comment]
ah, from what I understand he uses 3ds max and raftools while I use blender and SUI. 

@coldAmphibian can you try to import sona animations for me? I have been struggling with sona specifically and am not sure if its just my tools or the stuff provided from the game files

**Comment by coldAmphibian** [comment]
I think there's something wrong with how 3ds max exports the models, Notice how Lux and Ezreal are darker than the other models for some reason. I'll try Sona, but if you get the chance, could you redo Ezreal and Lux? I was talking to Swordzzz and I think using RAFtools and LoL2DAE fixes some broken animations/models.

**Comment by coldAmphibian** [comment]
Sona added

**Comment by Zarthbenn** [comment]
lux seems to import fine, im working on it right now. Ezreal straight up crashes blender when I try to import an animation for him (looking in to this). I tried importing sona using RAFTools and the broken animations still persist.

**Comment by Zarthbenn** [comment]
ok I think I understand what the issues are. I think 3ds max's default texture has some shading on it which causes whatever material applied to be darker. I found a free standalone program by autodesk http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=20481519 that converts dae to fbx pretty well and does not need 3ds max open. I redid lux and ezreal anyway, and I can probably do sona if you havent already (you didnt update the git with her models in).

Edit: Nvm not as big of a convenience as i thought, the converter works but I still end up having to import export things through blender. This does fix messed up frames in some animations though

Also shouldn't we leave this open incase someone wants a champ imported?

**Comment by coldAmphibian** [comment]
https://www.reddit.com/r/DefenseoftheLegends/wiki/importing_lol_models

**Comment by coldAmphibian** [comment]
I wrote a bit of a tutorial, you might want to add to it @Zarthbenn

**Comment by Zarthbenn** [comment]
should i just write that page or do you want to add anything?

**Comment by coldAmphibian** [comment]
I added some basic stuff, I'll add screenshots too. Cover the stuff I missed out on

**Comment by Zarthbenn** [comment]
hmm not showing up for me

**Comment by coldAmphibian** [comment]
![image](https://cloud.githubusercontent.com/assets/8411784/8769301/4a7c73d2-2edd-11e5-9b26-7ef94b9bf41b.png)

**Comment by Zarthbenn** [comment]
oh lol it does not show up in dark theme in RES

**Comment by Zarthbenn** [comment]
added some more stuff, Il do hitboxes and attachments later if someone else doesnt

**Comment by coldAmphibian** [comment]
Things are looking good in game
![image](https://cloud.githubusercontent.com/assets/8411784/8769326/e1d02044-2edd-11e5-849f-98a1497d3672.png)

**Comment by Zarthbenn** [comment]
yea i love how nice blitzcrank looks, i still dont have a good idea for what the model scale should be like so leona and taric might be too big/small

**Comment by coldAmphibian** [comment]
Scale how you think they should be, one of the things you'll notice is that in LoL, Sona's absolutely tiny. Increase the model size! :D

**Comment by coldAmphibian** [comment]
https://i.imgur.com/fPCE5sM.jpg

**Comment by Zarthbenn** [comment]
ok, did you ever get around to importing sona? I think i fixed what the issue with her was but you said you already added her in this thread

**Comment by coldAmphibian** [comment]
she should be in the latest commit

**Comment by Zarthbenn** [comment]
oh, in your branch. I see

**Comment by coldAmphibian** [comment]
i thought i merged master

**Comment by Zarthbenn** [comment]
i dont think so

**Comment by coldAmphibian** [comment]
![image](https://cloud.githubusercontent.com/assets/8411784/8769942/8e58838a-2eeb-11e5-8484-c424a6214bec.png)

**Comment by Zarthbenn** [comment]
not showing up on the commit list on the web, unless im really blind

**Comment by coldAmphibian** [comment]
you're right
that's odd

**Comment by Zarthbenn** [comment]
it says something about a conflict on your last commit in your branch

**Comment by coldAmphibian** [comment]
==U

**Comment by coldAmphibian** [comment]
it's not erroring for me for some reason, it just won't push

**Comment by coldAmphibian** [comment]
done

**Comment by wn-mitch** [comment]
so any change to the instructions based on the errors thrown?

**Comment by coldAmphibian** [comment]
What errors?

**Comment by wn-mitch** [comment]
Nvm, I was wondering if the errors that were getting thrown changed the instructions. I think.

**Comment by wfzyx** [comment]
Archived
