### ISSUE TITLE
Mundo Work in Progress

### ISSUE THREAD

**Issue by wn-mitch** [coldAmphibian/Defense-of-the-Legends#2]
I've started work on Dr. Mundo and am using this as a place to collect all of the work in progress items for him.
- Infected Cleaver does not slow
- Burning Agony does not reduce crowd control
- Sadism does not increase movement speed

I also have no idea how to test if my scripts even work, so any advice there would be much appreciated <3

**Comment by Capruce** [comment]
Create a blank addon with an empty map, then create your abilities and heroes and test them. Once it all starts to work then add them to this mod. At least I find that easier to work with.

Not really sure how to work with Tenacity and crowd control reductions, perhaps the new filters could help?

**Comment by wn-mitch** [comment]
I fixed most of the issues except for the CC which I'm not sure if it is possible to implement. I've added a ton of changes in my fork, haven't had a chance to test yet though

**Comment by wfzyx** [comment]
Its possible, but I'm not sure at the moment what is the best implementation, because is a generic mechanic of LoL, related to tenacity.

You can put a comment on the code, with a "TODO:" so we can check this later.

**Comment by wn-mitch** [comment]
Could someone help me test this? I'm having trouble getting the test environment to start properly :p

**Comment by Zarthbenn** [comment]
Not sure what specific problem you are having but just open a template map and F9 run it and your scripted hero should be there with its custom abilities.

**Comment by wfzyx** [comment]
@ChangedNameTo Use the modkit to generate a barebone, or just forkit at Myll/BMD/Noya repo, then copy your codes and run at hammer
