### ISSUE TITLE
Ezrael animations are borked

### ISSUE THREAD

**Issue by Numbers11** [coldAmphibian/Defense-of-the-Legends#21]
Video related.
http://gfycat.com/GreedyIdealFlicker

Also I try to learn the particle editor, do you think I am going in the right direction with these?

**Comment by wfzyx** [comment]
Please sync your local repo with latest version, the walk animations and stuff are fixed.

About your particles, yeap, they are looking great

**Comment by Numbers11** [comment]
thx
