### ISSUE TITLE
Draw Distance

### ISSUE THREAD

**Issue by coldAmphibian** [coldAmphibian/Defense-of-the-Legends#23]
In LoL, the draw distance seems a lot further than in Dota. Could someone look into getting it to be so? This way, the background stuff can be visible. Those are pretty. So far, I've found using "fogui" in the console gets the results I want, but I'd rather have it as something that automatically happens on game start.

**Comment by wn-mitch** [comment]
Is there a way to run console commands on game start?

**Comment by coldAmphibian** [comment]
fogui is sv_cheats 1 console command, I'm sure there's ways around it.

**Comment by wfzyx** [comment]
Archived
