### ISSUE TITLE
Leona

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#26]
- [ ] Missing particles
- [ ] Missing VO
- [ ] Missing SFX
- [x] Missing Card/portrait
- [ ] fix scale model
- [ ] fix unit scaling (spell range, projectile speeds)
- [x] Zenith blade not pulling leona forward
- [ ] ultimate delay too fast
- [ ] Q going on cd should be after landing hit or modifier expires
- [ ] Q resets attack timer
- [ ] E hitting multiple targets can be used to "drift" around, also everyone is putting to face Leona final position insted of initial

**Comment by Zarthbenn** [comment]
Fixing some of this stuff. How is the delay on the ult too fast? According to wiki the delay is 0.625 which is exactly what it is in AbilitySpecial. All the spell ranges follow the 550/750 rule found in the unit conversion page in the wiki. I will fix the speed and width of zenith blade

**Comment by wfzyx** [comment]
Don't take these tasklists too hard!

I checked the value, but for some reason it feels different from LoL, idk if the particle used have something to do about it, or wiki is just not updated with the current delay in-game of LoL.

All the ranges will need to be reviewed maybe, because idk about the map scaling of LoL in hammer, i'll talk later with @coldAmphibian about this, note I'm inserting this task on all lists because of the same reason.

The zenithblade behavior is directly related to the previous point.

**Comment by Zarthbenn** [comment]
alright, I agree with the ult feeling too fast but the numbers are the same. Il leave the ranges as is until we can all agree on a good ratio. Currently adding all missing cards/portraits

**Comment by wfzyx** [comment]
Your are talking about the top hud portraits right?

I'm referring to In game animated portrait too.

Also, idk if you saw, but the card is just showing when the animations is stopped, when highlighting the card, the normal animation still plays on

**Comment by Zarthbenn** [comment]
I got a fix for the loadout. Not sure how to fix the ingame portrait though. I couldn't find anything in the model editor relating to it and portrait debug mode from console seems to be broken.

**Comment by wfzyx** [comment]
Yeap its broken, I'm working on a workaround.

**Comment by wfzyx** [comment]
Idk if everyone agrees, but i think putting the default skin static image on all cards would be good as hell. better than using skinned small clips. what do you think @Zarthbenn ? btw, congratz, everything is looking very good

@coldAmphibian give your thought about it

**Comment by Zarthbenn** [comment]
I have no problem with that, I only used the skinned clips because I wanted to show how good an animated splash would be in the loadout. Would be great if we had someone to animate the default skins but until then il keep making the static ones.

**Comment by wfzyx** [comment]
Yeap i agree, if clips for all default skins exists, would be amazing =/

**Comment by coldAmphibian** [comment]
I could look into animating the default skins. Use RAFTools to look at each champion and spell's ".inibin" file. Those have the cast time and delays all in it. You just need to match them. If you ever see vs49688 on the irc or anywhere, he wrote RAFTools and can help you with that.

**Comment by wfzyx** [comment]
@Zarthbenn giff halp.

Zenithblade wasn't damaging creeps, so I changed and, found it was not retreating properly (not sure if i break it). I fixed the retreating now the animation plays correctly, But if there is units behing the hooker target, they still suffer from damage, and even worse, if another hero, leona gets pulled again T.T

Any idea?

**Comment by Zarthbenn** [comment]
this is intentional and how leona works.... Have you ever played her in league?

**Comment by Zarthbenn** [comment]
there also shouldn't be any retracting animation

**Comment by wfzyx** [comment]
Leona-(close distance)->Ez(invisible Zblade)----Blitz
Leona gets pulled into blitz.
This isn't correct afaik.

**Comment by Zarthbenn** [comment]
http://leagueoflegends.wikia.com/wiki/Leona

ACTIVE: Leona projects a solar image of her sword, dealing magic damage to all enemies in a line. **Leona will dash to the last enemy champion struck**, briefly Root icon rooting them in place as she travels. 

Unless im missing something

**Comment by wfzyx** [comment]
I'm dumb, sorry.

So the mechanic is right, but the animation isn't.

I'll fix, ty @Zarthbenn

**Comment by Zarthbenn** [comment]
No problem at all. Looking over the code you also might have mistakenly removed modifier_leona_sunlight from all her abilities except for her q (its part of her passive so it needs to be on everything)

**Comment by wfzyx** [comment]
Nope, isn't a mistake, it's coded on lua now, it's a more DRY approach.

**Comment by coldAmphibian** [comment]
Just pulled and tried out Leona, things to fix with this commit:
- Heroes don't level, they get forced on level 1
- Leona's Zenith blade doesn't snare everything it hits, just the last target
- In LoL, skillshots fire regardless of whether your target was out of range or not, currently, leona walks into range before using zenith blade

**Comment by Zarthbenn** [comment]
Is that last point something we can change though? I dont think I have ever seen an ability be able to target outside of the cast range, if thats something we can change then we will need to apply it to ezreal/blitzcrank or anyone with a projectile really.

**Comment by coldAmphibian** [comment]
Do you think you could hack it together in some way?

**Comment by Zarthbenn** [comment]
Personally I don't think so. Editing something like that seems to be a pretty fundamental part of the engine and goes beyond my limited knowledge of programming in dota. Unless there's a function like CastOutOfRange() = 1 it would probably be very difficult(but what do I know).

**Comment by coldAmphibian** [comment]
probs ask around the irc. I was thinking of doing a custom skillshot base class and working off that but that might be a bit complicated

**Comment by Capruce** [comment]
The only way would be to make all abilities have global range and then
calculate the angle etc in terms of cursor position. It would mean that
abilities would not have their range circles when hovered over though.

**Comment by coldAmphibian** [comment]
maybe a separate function for that too, seeing as LoL has it's own crosshair system
esp for heroes like anivia, velkoz etc. who have weird shaped crosshairs

**Comment by wfzyx** [comment]
I don't really think is a good idea tbh.

I think this is a flaw of LoL's design, and port this over would be weird in the best case scenario.

**Comment by Capruce** [comment]
I agree, I much prefer the way DotA handles it.

**Comment by coldAmphibian** [comment]
:I i have a differing opinion but whatevs.

**Comment by Capruce** [comment]
There is a subreddit :/ It feels weird getting a ton of emails from issue
tracking.

It's open to discuss obviously. I think to start off, we should be as
faithful as possible then begin to introduce tweaks. ?

**Comment by coldAmphibian** [comment]
pick whatever you're comfortable with i suppose

**Comment by gw1108** [comment]
For cold's last point, isn't that exactly how AM and QOP's blink abilities work? If you target outside of your range the "skillshot" (blink) will just fire as far as it can. Either that or we keep its behaviour like pudge's hook and Sand King's Q, where they walk so their skill shot is in range then cast it.

**Comment by Capruce** [comment]
Yes they have global cast range (0) and then the game calculates the
direction from the cursor position and the heroes position like I said
before.

**Comment by coldAmphibian** [comment]
so does antimage's blink have a range indicator?

**Comment by Capruce** [comment]
Nope, since the cast range is technically 0 in the code and that's what's
used to draw the circle.

**Comment by coldAmphibian** [comment]
I wonder if I can find a way to draw the ranges using LoL's assets

**Comment by wfzyx** [comment]
@coldAmphibian no hackerino coderino pls

**Comment by wfzyx** [comment]
Also, pls sthap flooding Leona's issue list, > [dicuss here](https://www.reddit.com/r/DefenseoftheLegends/comments/3eh7nk/discuss_about_port_the_lol_mech_to_cast_outside/)

**Comment by wfzyx** [comment]
Archived
