### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#31]
@coldAmphibian pls

![image](https://cloud.githubusercontent.com/assets/5880370/8886617/deac47b2-3243-11e5-87d5-b7b48b39c79d.png)

**Comment by coldAmphibian** [comment]
what... i fixed that, like twice already
check the commits

**Comment by wfzyx** [comment]
well, I'm not fully sure if i saw this after sync or before sync, i'll let you know or close this

**Comment by wfzyx** [comment]
![image](https://cloud.githubusercontent.com/assets/5880370/8887733/81a1421c-3265-11e5-989a-30b4cd68c77f.png)

@coldAmphibian again, now i'm sure it's post sync

**Comment by Zarthbenn** [comment]
^il just throw in that I sometimes have it too(current commit)

**Comment by coldAmphibian** [comment]
whaaaat.... check the commits, literally my last commit fixes this

**Comment by wfzyx** [comment]
Not telling you are lying, just saying still broken Keepo

**Comment by coldAmphibian** [comment]
https://github.com/coldAmphibian/Defense-of-the-Legends/blob/master/content/dota_addons/dotl_dev/panorama/images/custom_game/loading_screen/Anivia.png

https://github.com/coldAmphibian/Defense-of-the-Legends/blob/master/content/dota_addons/dotl_dev/panorama/scripts/custom_game/custom_loading_screen.js

**Comment by coldAmphibian** [comment]
that's just really odd

**Comment by wfzyx** [comment]
Seems like it got fixed.
