### ISSUE TITLE
Map things.

### ISSUE THREAD

**Issue by coldAmphibian** [coldAmphibian/Defense-of-the-Legends#33]
- [ ] Inhibitors - they need to respawn, using 2 rax is super dodgy
- [ ] Towers - they work differently to dota towers
- [ ] Runes - pref we could make the runes do what they do in HA, but this is secondary
- [ ] Nexuses - tweak health etc.
- [ ] Fountain - make the fountain laze baddies
- [ ] Shops - make them only accessible on spawn and not after
- [ ] Minions - replace their model animation etc. 
- [ ] Minion Spawners - spawn minions like they do in lol rather than dota

**Comment by coldAmphibian** [comment]
We need to get at least the inhibitors done by ship

**Comment by Zarthbenn** [comment]
all the minion models/animations are in the repo. There is some barbones stuff in npc_units_custom but it was set up to replace, so it needs some changes.

**Comment by wfzyx** [comment]
Most of this stuff can be done with timers listening to game events. @Capruce  and me can take care of this i think

**Comment by wfzyx** [comment]
Archived
