### ISSUE TITLE
STOP ADDING CHAMPIONS

### ISSUE THREAD

**Issue by coldAmphibian** [coldAmphibian/Defense-of-the-Legends#36]
![image](https://cloud.githubusercontent.com/assets/8411784/8899308/18df7a6a-3476-11e5-8483-dd86e4cce7f8.png)
SERIOUSLY, fix the ones that are in the game currently... please...

**Comment by Zarthbenn** [comment]
This is a great image to represent of the current state of the mod, you should post this on your blog.

but srsly tho il start working on polishing up the current ones, were close to hitting the cap for champion models anyway

**Comment by wfzyx** [comment]
Yes please, help me with polishing T.T

**Comment by coldAmphibian** [comment]
There's a cap for champion models?

**Comment by coldAmphibian** [comment]
And I will post it on my blog

**Comment by wfzyx** [comment]
Archived
