### ISSUE TITLE
"X on next autoattack" Abilities

### ISSUE THREAD

**Issue by Zarthbenn** [coldAmphibian/Defense-of-the-Legends#38]
This is concerning abilities like Leona's Shield of Daybreak, Blitzcrank's Power fist and Garen's Decisive Strike (and similar).

The way these abilities work in league goes as follows:

-> Ability Cast 
-> Apply Appropriate Modifier for a duration + Disable Ability from being used or going on cooldown
-> Autoattack hit OR Duration for modifier expires (a successful autoattack never happened)
-> Remove modifier + Re-enable ability so it goes on cooldown.

The issue that I am having is creating a way to disable the ability for the duration of the modifier. During the modifier's lifespan the ability should not be able to cast or be on cooldown. A rough solution would be to extend the cooldown of the ability by the duration of the modifier (how swordzz did it for Garen) but its not very effective (can be abused by cdr and the such).

Ideally (although not really) there would be some sort of DisableAbility() function that we could run at creation of the modifier and reverse it at the end. To my knowledge there is not such a function. 

Not really sure where to go from here. I might be missing some really simple solution or something else but I feel that this is a very specific ability behavior from league that should be implemented.

**Comment by gw1108** [comment]
Spirit Breaker's Charge of Darkness works in a similar way where they delay the cooldown until the ability is cancelled or is successful. Not sure how they did that though.

**Comment by Zarthbenn** [comment]
I forgot about that move! Unfortunately pizzalols spell library doesn't have it ported yet so we got to figure it out ourselves.

**Comment by wfzyx** [comment]
you probably need to add a hidden ability with the same kv descriptor but with the "toggle" behavior, like Leshrac's ult for e.g , then OnSpellStart of the real ability, you mark the ability as hidden, apply the modififer, and UnHidden the fake one with the "toogle behavior". You need to have a OnToogle on this ability to prevent activating/deactivating the ability for abuses, When modifier runs off, you set hidden on the fake one, unhidden the original an set cooldown manually.

**Comment by wfzyx** [comment]
Probably there is a way to make this with only the real spell, marking as toggle, preventing untoggle and set cooldown manually, but i'm not fully sure

**Comment by wn-mitch** [comment]
Have you guys seen the Spell Factory repository? You might be able to steal
the code from there.

**Comment by wfzyx** [comment]
Giff Link @ChangedNameTo my google-fu skills failed on finding this

**Comment by gw1108** [comment]
He might be talking about this : https://github.com/Pizzalol/SpellLibrary

**Comment by wfzyx** [comment]
This is exactly what we are talking earlier ._.

**Comment by coldAmphibian** [comment]
what about how old tusks's walrus punch worked?

**Comment by wn-mitch** [comment]
Well I'm retarded.

**Comment by wfzyx** [comment]
Archived
