### ISSUE TITLE
Css error

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#39]
![image](https://cloud.githubusercontent.com/assets/5880370/10397117/74ce96a4-6e7c-11e5-8ab3-ab9f4d5090f7.png)

paging @coldAmphibian

**Comment by Zarthbenn** [comment]
Piggy backing on this issue (another minor error). I think garen has the same hero ID as arc warden, it shows an error whenever game is loaded up and crashes for me. (I would fix it myself but I have not worked with the files for some time so I dont want to mess with anything that might break something else)

**Comment by wfzyx** [comment]
Pull the latest commit, already fixed
