### ISSUE TITLE
Overlapping Overrides

### ISSUE THREAD

**Issue by wn-mitch** [coldAmphibian/Defense-of-the-Legends#4]
While not an issue right now, we need to keep track of which champ we are overriding so we don't end up with compiler conflicts where 2 champs override the same champion, ie having two champions with an     "override_hero"         "npc_dota_hero_alchemist" tag

**Comment by wfzyx** [comment]
This isn't top level issue, because you just need to change 1 line, and nothing else really conflicts.

If happens we chose one to change, no worry about

**Comment by Capruce** [comment]
Might I suggest an additional column on the wiki page where people say what hero they're working on. Write down which hero you're overriding. Simple.

**Comment by Capruce** [comment]
Here. https://github.com/coldAmphibian/DotL-Hammer-Old/wiki/Hero-Overriding

**Comment by wn-mitch** [comment]
Good thinking, I'm gonna close this
