### ISSUE TITLE
How to build and run dotl?

### ISSUE THREAD

**Issue by ninjaHoa** [coldAmphibian/Defense-of-the-Legends#41]
Hi, 

I've downloaded this repository and opened howling_abyss_45.vmap using the hammer editor, however, it's all red lines.

![redhowlingabyss](https://cloud.githubusercontent.com/assets/22913095/19479406/14a8486c-958e-11e6-90dd-ec00a6f62c08.png) 

After building it and getting in game, it's not an actual map like your tumblr posts.

![howlingabyss in game](https://cloud.githubusercontent.com/assets/22913095/19479425/35e17940-958e-11e6-96fb-adb321c81343.png)

What am I  doing wrong? How do I get the game to use the actually howling abyss map?

**Comment by wfzyx** [comment]
Archived
