### ISSUE TITLE
Having an issue setting a target from modifier.

### ISSUE THREAD

**Issue by Zarthbenn** [coldAmphibian/Defense-of-the-Legends#5]
I am currently working on Leona and am having an issue with her passive. I tried several things that did not work and cant find anyone else that has the same problem. Not sure if this is the right place to post this, but it is part of the mod.

Ideally whenever leona casts an ability her sunlight passive applies from the passive and not the ability. Unfortunately there does not seem to be the equivalent of OnAttackLanded (something like OnSpellHit) so the sunlight debuff must be applied manually from each individual ability.

Here is the modifier:

```
"modifier_leona_sunlight"
            {
                "IsDebuff"      "1"
                "Duration"      "3.5"

                "EffectName"        "particles/units/heroes/hero_legion_commander/legion_commander_duel_buff.vpcf"
                "EffectAttachType"  "follow_origin" 

                "OnTakeDamage"
                {
                    "RemoveModifier"
                    {
                        "ModifierName"  "modifier_leona_sunlight"
                    }
                    "Damage"
                    {
                        "Target"        "TARGET"
                        "Type"          "DAMAGE_TYPE_MAGICAL"
                        "Damage"        "200"
                    }

                }
            }
```

The issue that I am having concerns the "Damage" portion of the modifier. Setting it to TARGET does not work (it returns an error:TARGET is not a recognized target name in modifier_leona_sunlight.), setting it to CASTER deals the damage to leona instead, and setting it to UNIT instakills whenever the modifier is applied for whatever reason.

The damage amount and particle is placeholder. I have worked on this problem for two days now and cant find anyway to get the "Target" of whoever the modifier is attached to.

**Comment by Capruce** [comment]
Not by a pc but I have some odeas you can try.

Firstly (not sure if this works) call a script function from the OnTakeDamage block and see what keys.target refers to (assuming your parameter is keys) by printing its name. If this doesn't refer to target then check if keys.target refers to it from the OnCreated block of the modifier.

**Comment by Zarthbenn** [comment]
Thank you for your help, I tried printing the target with OnCreated and it worked. After that I found out that it was OnTakeDamage that was acting strangely and not giving the target, I switched it to OnAttacked (which in hindsight is what I should have used initially) and it works like intended now.
