### ISSUE TITLE
Champion Passives

### ISSUE THREAD

**Issue by Capruce** [coldAmphibian/Defense-of-the-Legends#6]
I've been playing around with having heroes have their passive abilities leveled at the start of the game.

There are 2 approaches to take, have the passive as ability 1 with behavior Hidden so as not to appear on the hud ( and therefore shift ability keybinds) and just setlevel of every champion to 1. OR
Have the ability specified on the hero as "Passive" "passive_name" and then add the ability on and set level to 1.

Atm I have the former set up but the second one is easy enough to also to do.
I need to know which you guys would prefer and also for you to edit your champion definitions to match the chosen format so that they can be automatically leveled.

Also, I have my passive's buff to display the necessary information about it ATM.
In the future we can display the passive (without the need of a visible buff) using panorama.

**Comment by wfzyx** [comment]
I thouhg on making a mini panorama overlay, but this would involve making cooldown, no-mana restrictions and so on.

the former is what i used most of the time, but the second approach i didn't knew about it.

Can you link me a example ?

**Comment by Capruce** [comment]
Don't have an example readily available but it involves loading in the KV file npc_heroes_custom and testing to see which hero has override of the hero that just  joined. It then does AddAbility of the name of the ability under "Passive" and then sets the level of the ability to 1.

**Comment by Capruce** [comment]
Would anyone mind if we renamed the ability special for learning an ability at level one? Abilities like Karma's ultimate require a point at the start of the game and it seems weird giving it champion_passive.  Any thoughts?

**Comment by Capruce** [comment]
Ok so any ability that needs to be available at the start of the game, such as passives or Karma's ultimate will need the "auto_learn" "1" ability special instead of "champion_passive" "1". Their use is identical the change was simply to clarify what it can be used for.

**Comment by wfzyx** [comment]
replaced on my local files, i'll commit soon™
